=== tassiovale/sgd-migration-tool/docs/XML/Arquivos Exportados/ControleAvaliacaoDocente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="ControleAvaliacaoDocente" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="ControleAvaliacaoDocente">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="nCodigoDocente nAvaliacao " primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="nCodigoDocente" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="nAvaliacao" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="nCodigoCurso" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="DtEntregaArea" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="DtEntregaCurso" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="DtEntregaDiretor" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tassiovale/sgd-migration-tool/docs/XML/Arquivos Exportados/ControleAvaliacaoDocente.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="ControleAvaliacaoDocente.xsd" generated="2015-09-30T15:05:12">
<ControleAvaliacaoDocente>
<nCodigoDocente>1</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>4</nCodigoCurso>
<DtEntregaArea>2015-02-20T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-23T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-25T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>3</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
<DtEntregaArea>2015-02-05T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-06T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-09T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>4</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>4</nCodigoCurso>
<DtEntregaArea>2015-02-20T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-11T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-25T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>5</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
<DtEntregaArea>2015-03-17T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-18T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-20T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>6</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>7</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>4</nCodigoCurso>
<DtEntregaArea>2015-02-20T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-23T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-25T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>10</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
<DtEntregaArea>2015-02-04T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-06T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-09T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>15</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>6</nCodigoCurso>
<DtEntregaArea>2015-02-05T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-12T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-12T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>16</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>4</nCodigoCurso>
<DtEntregaArea>2015-02-20T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-23T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-25T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>17</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>7</nCodigoCurso>
<DtEntregaCurso>2015-02-20T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-20T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>18</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
<DtEntregaArea>2015-02-04T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-06T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-09T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>20</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>21</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>22</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
<DtEntregaArea>2015-02-20T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-06T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-09T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>24</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>4</nCodigoCurso>
<DtEntregaArea>2015-02-20T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-13T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-25T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>13</nCodigoDocente>
<nAvaliacao>201302</nAvaliacao>
<DtEntregaArea>2015-03-06T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-06T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-09T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>13</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>9</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>5</nCodigoCurso>
<DtEntregaArea>2015-02-05T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-05T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-05T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>8</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>5</nCodigoCurso>
<DtEntregaArea>2015-02-05T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-05T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-05T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>19</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>3</nCodigoCurso>
<DtEntregaArea>2015-02-04T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-02-19T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-02-19T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>11</nCodigoDocente>
<nAvaliacao>201401</nAvaliacao>
<nCodigoCurso>1</nCodigoCurso>
<DtEntregaArea>2015-03-17T00:00:00</DtEntregaArea>
<DtEntregaCurso>2015-03-18T00:00:00</DtEntregaCurso>
<DtEntregaDiretor>2015-03-20T00:00:00</DtEntregaDiretor>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>17</nCodigoDocente>
<nAvaliacao>201505</nAvaliacao>
</ControleAvaliacaoDocente>
<ControleAvaliacaoDocente>
<nCodigoDocente>13</nCodigoDocente>
<nAvaliacao>201505</nAvaliacao>
</ControleAvaliacaoDocente>
</dataroot>
