=== tassiovale/sgd-migration-tool/docs/XML/Arquivos Exportados/Docente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Docente" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Docente">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="nCodigoDocente " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="AreaDocente" index-key="nCodigoArea " primary="no" unique="no" clustered="no"/>
<od:index index-name="Carga HorariaDocente" index-key="nCargaHoraria " primary="no" unique="no" clustered="no"/>
<od:index index-name="Classe DocenteDocente" index-key="nCodigoClasse " primary="no" unique="no" clustered="no"/>
<od:index index-name="DocentenCodigoTitulacao" index-key="nCodigoTitulacao " primary="no" unique="no" clustered="no"/>
<od:index index-name="Nivel da ClasseDocente" index-key="nCodigoNivel " primary="no" unique="no" clustered="no"/>
<od:index index-name="Origem VagaDocente" index-key="nCodigoOrigemVaga " primary="no" unique="no" clustered="no"/>
<od:index index-name="TitulacaoDocente" index-key="nCodigoTitulacao " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="nCodigoDocente" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="nMatriculaSiape" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="sNomeDocente" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="dDataIngresso" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="nCodigoArea" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="lEntregouPTT" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="lAprovadoEstagio" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="dDataDesligamento" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="sMotivoDesligamento" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="OrigemDocente" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nCodigoClasse" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="nCodigoNivel" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="nCodigoTitulacao" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="nCodigoOrigemVaga" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="sObsOrigemVaga" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sEmail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sObservacaoEstagio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="nCargaHoraria" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="dDataIngressoCETEC" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="UtilizaraGabinete" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="nTelefone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== tassiovale/sgd-migration-tool/docs/XML/Arquivos Exportados/Docente.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Docente.xsd" generated="2015-09-30T15:05:49">
<Docente>
<nCodigoDocente>1</nCodigoDocente>
<nMatriculaSiape>1932340</nMatriculaSiape>
<sNomeDocente>ACBAL RUCAS ANDRADE ACHY</sNomeDocente>
<dDataIngresso>2013-05-09T00:00:00</dDataIngresso>
<nCodigoArea>7</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>acbal@ufrb.edu.br;acbal.achy@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-05-09T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>2</nCodigoDocente>
<nMatriculaSiape>1846601</nMatriculaSiape>
<sNomeDocente>ADILSON GOMES DOS SANTOS</sNomeDocente>
<dDataIngresso>2011-02-08T00:00:00</dDataIngresso>
<nCodigoArea>4</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>1</lAprovadoEstagio>
<nCodigoClasse>3</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>adilsongomes@ufrb.edu.br;adigomes@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2011-02-08T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>0</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>3</nCodigoDocente>
<nMatriculaSiape>1496556</nMatriculaSiape>
<sNomeDocente>ADILSON BRITO DE ARRUDA FILHO</sNomeDocente>
<dDataIngresso>2013-10-11T00:00:00</dDataIngresso>
<nCodigoArea>1</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>3</nCodigoTitulacao>
<sEmail>adilson.arruda@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-10-11T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>4</nCodigoDocente>
<nMatriculaSiape>2126496</nMatriculaSiape>
<sNomeDocente>CAROLINA MORENO SALCEDO NUNES</sNomeDocente>
<dDataIngresso>2014-05-19T00:00:00</dDataIngresso>
<nCodigoArea>7</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>carolina.nunes@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2014-05-19T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>5</nCodigoDocente>
<nMatriculaSiape>1527551</nMatriculaSiape>
<sNomeDocente>CLÉLIO BRASIL CARDOSO GOMES</sNomeDocente>
<dDataIngresso>2013-04-17T00:00:00</dDataIngresso>
<nCodigoArea>8</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<sEmail>cleliogomes@ufrb.edu.br;gcbc8@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-04-17T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>6</nCodigoDocente>
<nMatriculaSiape>2142184</nMatriculaSiape>
<sNomeDocente>EDWIN HOBI JÚNIOR</sNomeDocente>
<dDataIngresso>2014-07-24T00:00:00</dDataIngresso>
<nCodigoArea>8</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>2</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<nCodigoOrigemVaga>3</nCodigoOrigemVaga>
<sEmail>edwin@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2014-07-24T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>7</nCodigoDocente>
<nMatriculaSiape>1583908</nMatriculaSiape>
<sNomeDocente>IGOR DANTAS DOS SANTOS MIRANDA</sNomeDocente>
<dDataIngresso>2013-10-30T00:00:00</dDataIngresso>
<nCodigoArea>7</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>igordantas@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-10-30T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>8</nCodigoDocente>
<nMatriculaSiape>2075385</nMatriculaSiape>
<sNomeDocente>JANAILSON OLIVEIRA CAVALCANTI</sNomeDocente>
<dDataIngresso>2013-12-02T00:00:00</dDataIngresso>
<nCodigoArea>1</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>4</nCodigoTitulacao>
<sEmail>janailsonoliver@ufrb.edu.br;janailsonoliver@yahoo.com.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-12-02T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>9</nCodigoDocente>
<nMatriculaSiape>2072268</nMatriculaSiape>
<sNomeDocente>JANIA BETANIA ALVES DA SILVA</sNomeDocente>
<dDataIngresso>2013-11-18T00:00:00</dDataIngresso>
<nCodigoArea>1</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<sEmail>janiabetania@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-11-18T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>10</nCodigoDocente>
<nMatriculaSiape>2075295</nMatriculaSiape>
<sNomeDocente>JAQUELINE ALEXSANDRA DE SOUZA AZEVEDO</sNomeDocente>
<dDataIngresso>2013-11-27T00:00:00</dDataIngresso>
<nCodigoArea>4</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>jaqueline_azevedo@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-11-27T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>11</nCodigoDocente>
<nMatriculaSiape>1878419</nMatriculaSiape>
<sNomeDocente>JILVAN LEMOS DE MELO</sNomeDocente>
<dDataIngresso>2014-08-06T00:00:00</dDataIngresso>
<nCodigoArea>8</nCodigoArea>
<lEntregouPTT>0</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>2</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<nCodigoOrigemVaga>3</nCodigoOrigemVaga>
<sEmail>jilvanlm@ufrb.edu.br</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2014-08-06T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>12</nCodigoDocente>
<nMatriculaSiape>1645120</nMatriculaSiape>
<sNomeDocente>JOAO CLAUDIO COSTA PEREIRA</sNomeDocente>
<dDataIngresso>2011-02-21T00:00:00</dDataIngresso>
<nCodigoArea>8</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>1</lAprovadoEstagio>
<nCodigoClasse>3</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<sEmail>jclaudiocp@ufrb.edu.br;jotaclaudiocp@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2011-02-21T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>13</nCodigoDocente>
<nMatriculaSiape>1526832</nMatriculaSiape>
<sNomeDocente>KARINA ARAUJO KODEL</sNomeDocente>
<dDataIngresso>2013-05-06T00:00:00</dDataIngresso>
<nCodigoArea>8</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<sEmail>karinakodel@ufrb.edu.br;kkodel@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-05-06T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>14</nCodigoDocente>
<nMatriculaSiape>1844127</nMatriculaSiape>
<sNomeDocente>LOURENCO GOBIRA ALVES</sNomeDocente>
<dDataIngresso>2011-02-04T00:00:00</dDataIngresso>
<nCodigoArea>1</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>1</lAprovadoEstagio>
<nCodigoClasse>2</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>1</nCodigoTitulacao>
<sEmail>lgobira@ufrb.edu.br;lgobira@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2011-02-04T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>15</nCodigoDocente>
<nMatriculaSiape>2032825</nMatriculaSiape>
<sNomeDocente>LUCIANA MACIEL BOEIRA</sNomeDocente>
<dDataIngresso>2013-11-01T00:00:00</dDataIngresso>
<nCodigoArea>1</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>lucianamb@ufrb.edu.br;luciana.boeira@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-11-01T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>16</nCodigoDocente>
<nMatriculaSiape>1685613</nMatriculaSiape>
<sNomeDocente>LUIZ CARLOS SIMÕES SOARES JÚNIOR</sNomeDocente>
<dDataIngresso>2013-11-08T00:00:00</dDataIngresso>
<nCodigoArea>7</nCodigoArea>
<lEntregouPTT>1</lEntregouPTT>
<lAprovadoEstagio>0</lAprovadoEstagio>
<nCodigoClasse>4</nCodigoClasse>
<nCodigoNivel>1</nCodigoNivel>
<nCodigoTitulacao>2</nCodigoTitulacao>
<sEmail>lcsimoes@ufrb.edu.br;simoeslc@gmail.com</sEmail>
<nCargaHoraria>3</nCargaHoraria>
<dDataIngressoCETEC>2013-11-08T00:00:00</dDataIngressoCETEC>
<UtilizaraGabinete>1</UtilizaraGabinete>
</Docente>
<Docente>
<nCodigoDocente>17</nCodigoDocente>
<nMatriculaSiape>1566826</nMatriculaSiape>
<sNomeDocente>MARIANA PINHEIRO GOMES DA SILVA</sNomeDocente>
